on:
  pull_request:
  push:

name: Check

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0

  tests:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run test suite
        run: bash test_arma3helper.sh
